#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Check if at least one argument is provided
# $1 is the path to file
# $2 is the IP
# $3 is the username
# $4 path to ssh key
# ./0-transfer_file some_page.html 100.26.174.108 ubuntu ~/.ssh/school

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp  -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
