#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect some requirements
sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /data/web_static/releases/test/index.html
sudo service nginx restart
