#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
sudo service nginx status >/dev/null 2>&1 && sudo service nginx stop
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
